import { StyleSheet } from 'react-native';
import { COLORS, SIZES } from '@constants';

export default StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: COLORS.white,
  },
  title: {
    fontSize: 28,
    textAlign: 'center',
    marginVertical: 22,
    fontWeight: '700',
  },
  subtitle: {
    fontSize: 16,
    textAlign: 'center',
    paddingHorizontal: 3,
    color: COLORS.gray,
    lineHeight: 24,
  },
  backButton: {
    padding: 8,
    marginBottom: 16,
  },
  backIcon: {
    width: 24,
    height: 24,
    tintColor: COLORS.primary,
  },
  scanView: {
    alignItems: 'center',
    marginVertical: 32,
  },
  scanContainer: {
    width: '100%',
    maxWidth: 350,
    aspectRatio: 1,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: COLORS.grayscale200,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  scanText: {
    fontSize: 18,
    marginBottom: 20,
    color: COLORS.primary,
    fontWeight: '600',
  },
  scanPlaceholderIcon: {
    height: 120,
    width: 120,
    tintColor: COLORS.primary,
    opacity: 0.8,
  },
  scannerContainer: {
    width: '100%',
    aspectRatio: 1,
    maxWidth: 350,
    borderRadius: 24,
  },
  scanButton: {
    alignItems: 'center',
    padding: 20,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
  },
  camera: {
    width: '100%',
    height: '100%',
  },
  centerText: {
    fontSize: 16,
    padding: 16,
    color: COLORS.gray,
    textAlign: 'center',
    lineHeight: 24,
  },
  rectangleContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  scannerBorder: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderColor: COLORS.primary,
  },
  topLeft: {
    top: 0,
    left: 0,
    borderTopWidth: 4,
    borderLeftWidth: 4,
  },
  topRight: {
    top: 0,
    right: 0,
    borderTopWidth: 4,
    borderRightWidth: 4,
  },
  bottomLeft: {
    bottom: 0,
    left: 0,
    borderBottomWidth: 4,
    borderLeftWidth: 4,
  },
  bottomRight: {
    bottom: 0,
    right: 0,
    borderBottomWidth: 4,
    borderRightWidth: 4,
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 32,
    width: '100%',
    maxWidth: 350,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: COLORS.grayscale200,
  },
  dividerText: {
    marginHorizontal: 12,
    color: COLORS.gray,
    fontSize: 14,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  manualButton: {
    width: '100%',
    maxWidth: 350,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  manualButtonText: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.primary,
    marginBottom: 4,
  },
  manualButtonSubtext: {
    fontSize: 14,
    color: COLORS.gray,
    textAlign: 'center',
    lineHeight: 20,
  },
  bottomContentContainer: {
    alignItems: 'center',
    paddingTop: 16,
    width: '100%',
  },
  manualInputButton: {
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 8,
    paddingHorizontal: 20,
    paddingVertical: 12,
    marginTop: 16,
  },
  manualInputButtonText: {
    color: COLORS.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  manualInputContainer: {
    width: '100%',
    maxWidth: 350,
    padding: 24,
    backgroundColor: COLORS.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.grayscale200,
    shadowColor: COLORS.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  manualInputTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: COLORS.dark,
    marginBottom: 8,
    textAlign: 'center',
  },
  manualInputSubtitle: {
    fontSize: 15,
    color: COLORS.gray,
    marginBottom: 24,
    textAlign: 'center',
    lineHeight: 22,
  },
  manualInput: {
    width: '100%',
    height: 56,
    borderWidth: 1.5,
    borderColor: COLORS.grayscale200,
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    backgroundColor: COLORS.white,
    marginBottom: 16,
    color: COLORS.dark,
  },
  manualInputButtons: {
    width: '100%',
    gap: 12,
  },
  button: {
    width: '100%',
    height: 56,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  submitButton: {
    backgroundColor: COLORS.primary,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  submitButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
  closeScanner: {
    backgroundColor: COLORS.primary,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
    marginTop: 10
  },
  closeScannerText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
  cancelButton: {
    backgroundColor: COLORS.white,
    borderWidth: 1.5,
    borderColor: COLORS.grayscale200,
  },
  cancelButtonText: {
    color: COLORS.dark,
    fontSize: 16,
    fontWeight: '600',
  },
  // Error state
  inputError: {
    borderColor: COLORS.error,
  },
  errorText: {
    color: COLORS.error,
    fontSize: 14,
    marginTop: -8,
    marginBottom: 16,
    alignSelf: 'flex-start',
  },
  page2: {
    width: '100%',
    aspectRatio: 1,
    maxWidth: 350,
    borderRadius: 24
  }
});